JANA:MAX_RELAUNCH_THREADS 10
REST:WRITE_DIRC_HITS 1
FDC:MATCH_TRUTH_HITS 1
PLUGINS monitoring_hists,danarest,truth_dirc,dirc_hists,dirc_reactions,dirc_tree,TrackMLextract,FCALextract
JANA_CALIB_CONTEXT "variation=mc"
DIRC:DEBUG_HISTS 0
DIRC_LUT /sciclone/home/jgiroux/gluex_top/lut/lut_all_flat.root
